server:
  port: 8081

spring:
  application:
    version: 1.0.0
    
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin123}@${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: notificationEvent:com.marcos.usersservice.event.NotificationEvent

kafka:
  topics:
    notifications: notifications

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, refresh
      base-path: /actuator