spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://configadmin:configsecret@localhost:8888
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.marcos.notificationservice.dto
        spring.json.value.default.type: com.marcos.notificationservice.dto.NotificationEvent
        spring.json.type.mapping: notificationEvent:com.marcos.notificationservice.dto.NotificationEvent
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:noreply@leairning.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8085

kafka:
  topics:
    notifications: notifications

notification:
  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100

eureka:
  client:
    enabled: false
