spring:
  application:
    name: leairning

  datasource:
    url: jdbc:postgresql://localhost:5432/leairningdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update

  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: hnsw
        distance_type: cosine_distance
        dimensions: 1536

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB