server:
  port: 8086

spring:
  application:
    name: chat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:http://${CONFIG_USER:configadmin}:${CONFIG_PASSWORD:configsecret}@${CONFIG_HOST:localhost}:8888
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 5m
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: documents


logging:
  level:
    org:
      zalando:
        logbook: TRACE

logbook:
  format:
    style: http
