spring:
  application:
    name: chat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:http://${CONFIG_USER:configadmin}:${CONFIG_PASSWORD:configsecret}@${CONFIG_HOST:localhost}:8888

# Fallback for local development without config-server
server:
  port: 8086

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: http